{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3d8991ee-75c2-4bf6-b697-a490f7aab3d7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Listening...\n",
      "Listening...\n",
      "Listening...\n",
      "Listening...\n",
      "Listening...\n",
      "Listening...\n",
      "You said: hello\n",
      "Listening...\n",
      "You said: what is the time\n",
      "Listening...\n",
      "You said: what is the date today\n",
      "Listening...\n",
      "Listening...\n",
      "Listening...\n",
      "You said: open youtube\n",
      "Listening...\n"
     ]
    }
   ],
   "source": [
    "import speech_recognition as sr\n",
    "import pyttsx3\n",
    "import datetime\n",
    "import webbrowser\n",
    "\n",
    "# Initialize voice engine\n",
    "engine = pyttsx3.init()\n",
    "engine.setProperty('rate', 170)\n",
    "\n",
    "def speak(text):\n",
    "    engine.say(text)\n",
    "    engine.runAndWait()\n",
    "\n",
    "# Initialize recognizer\n",
    "r = sr.Recognizer()\n",
    "\n",
    "speak(\"Hello, I am your AI voice assistant. How can I help you?\")\n",
    "\n",
    "while True:\n",
    "    try:\n",
    "        with sr.Microphone() as source:\n",
    "            print(\"Listening...\")\n",
    "            audio = r.listen(source)\n",
    "            command = r.recognize_google(audio).lower()\n",
    "            print(\"You said:\", command)\n",
    "\n",
    "        # TIME\n",
    "        if \"time\" in command:\n",
    "            time = datetime.datetime.now().strftime(\"%I:%M %p\")\n",
    "            speak(f\"The time is {time}\")\n",
    "\n",
    "        # DATE\n",
    "        elif \"date\" in command:\n",
    "            date = datetime.datetime.now().strftime(\"%d %B %Y\")\n",
    "            speak(f\"Today's date is {date}\")\n",
    "\n",
    "        # OPEN GOOGLE\n",
    "        elif \"open google\" in command:\n",
    "            speak(\"Opening Google\")\n",
    "            webbrowser.open(\"https://www.google.com\")\n",
    "\n",
    "        # OPEN YOUTUBE\n",
    "        elif \"open youtube\" in command:\n",
    "            speak(\"Opening YouTube\")\n",
    "            webbrowser.open(\"https://www.youtube.com\")\n",
    "\n",
    "        # YOUTUBE SEARCH\n",
    "        elif \"search youtube\" in command:\n",
    "            speak(\"What should I search on YouTube?\")\n",
    "            with sr.Microphone() as source:\n",
    "                audio = r.listen(source)\n",
    "                query = r.recognize_google(audio)\n",
    "                speak(f\"Searching YouTube for {query}\")\n",
    "                webbrowser.open(f\"https://www.youtube.com/results?search_query={query}\")\n",
    "\n",
    "        # AI RESPONSES (RULE BASED)\n",
    "        elif \"your name\" in command:\n",
    "            speak(\"I am an AI voice assistant created by you\")\n",
    "\n",
    "        elif \"who created you\" in command:\n",
    "            speak(\"You created me using Python and artificial intelligence\")\n",
    "\n",
    "        elif \"what is ai\" in command:\n",
    "            speak(\"Artificial Intelligence is the ability of machines to think and act like humans\")\n",
    "\n",
    "        elif \"how are you\" in command:\n",
    "            speak(\"I am doing great. Thank you for asking\")\n",
    "\n",
    "        # EXIT\n",
    "        elif \"stop\" in command or \"bye\" in command or \"exit\" in command:\n",
    "            speak(\"Goodbye. Have a great day\")\n",
    "            break\n",
    "\n",
    "        else:\n",
    "            speak(\"Sorry, I did not understand that. Please try again\")\n",
    "\n",
    "    except:\n",
    "        speak(\"Please say that again\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "68e44100-7860-4787-be65-e19b79851fb5",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0460d751-eada-41c6-a1d4-40df46f9c166",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1d1c4582-c174-4574-b8e6-35ff90cab877",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
